# Generated by Django 5.2.12 on 2026-07-23 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salonuser',
            name='wallet_balance',
        ),
    ]
